### ISSUE TITLE
As a developer I want to be able to set minification to my bundle when I run tests

### ISSUE THREAD

**Issue by sospirited** [BladeRunnerJS/brjs#339]
This use case comes from a developer who wants to create their own application user library and run their tests for it, minified - to see that it continues to pass and give them confidence that when it gets exported as a WAR etc (with closure-simple for example) - it will continue to work as expected.

At the moment the `jsTestDriver.conf` has the plugin defined as this:

```
plugin:
  - name: "BundleInjector"
    jar: ../../../../../../sdk/libs/java/testRunner/js-test-driver-bundler-plugin.jar
    module: com.caplin.jstestdriver.plugin.CutlassBundleInjectorPlugin
```

The thinking was that we could potentially pass in a parameter when we call the plugin jar which allows us to control the minification:

```
    jar: ../../../../../../sdk/libs/java/testRunner/js-test-driver-bundler-plugin.jar -Dminifier="closure-simple"
```

Due to how the `jsTestDriver.conf` needs to know the files to load up-front, it means we still won't be able serving up individual files for testing, but would still allow us to serve up different minifications which are still concatenations of JS content.
